@startuml
hide empty description

/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "CSharp"
'/

' 1. The Happy Path
[*] --> CREATED
CREATED --> WAITING_TO_RUN : ACTIVATED
WAITING_TO_RUN --> RUNNING : START_RUNNING
RUNNING --> RAN_TO_COMPLETION : COMPLETED_SUCCESSFULLY

' 2. Loops and Retries
RAN_TO_COMPLETION -up-> WAITING_TO_RUN : RUN_AGAIN
FAULTED -up-> WAITING_TO_RUN : RECOVER_RETRY

' 3. Side Processes
CREATED -right-> WAITING_FOR_ACTIVATION : GET_READY
WAITING_FOR_ACTIVATION --> WAITING_TO_RUN : ACTIVATED

RUNNING -right-> WAITING_FOR_CHILDREN_TO_COMPLETE : CHILD_TASK_CREATED
WAITING_FOR_CHILDREN_TO_COMPLETE -left-> RUNNING : ALL_CHILDREN_COMPLETED

' 4. Error Handling
RUNNING -left-> FAULTED : UNABLE_TO_COMPLETE
WAITING_FOR_CHILDREN_TO_COMPLETE --> FAULTED : UNABLE_TO_RECOVER

' 5. Cancellation (The Sink)

CREATED --> CANCELED : CANCEL
WAITING_FOR_ACTIVATION --> CANCELED : CANCEL
WAITING_TO_RUN --> CANCELED : CANCEL
RUNNING --> CANCELED : CANCEL
WAITING_FOR_CHILDREN_TO_COMPLETE --> CANCELED : CANCEL
FAULTED --> CANCELED : UNABLE_TO_RECOVER

@enduml