// Autogenerated with StateSmith 0.19.0-alpha-1+5931a3a68e50c80e83349118a90569bf08270686.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms



namespace GameVariable.Intent;

// Generated state machine
/// <summary>
/// A high-performance, zero-allocation Hierarchical State Machine (HSM) for managing game AI behaviors.
/// </summary>
public partial struct IntentState : IIntent<IntentState.StateId, IntentState.EventId>
{

    /// <summary>
    /// Events that trigger state transitions in the intent machine.
    /// </summary>
    public enum EventId
    {
        /// <summary>Aborts a blocked intent, moving it to FAULTED.</summary>
        ABORT = 0,
        /// <summary>Activates a created or inactive intent, moving it to PENDING.</summary>
        ACTIVATE = 1,
        /// <summary>Cancels the intent from any state, moving it to CANCELLED.</summary>
        CANCEL = 2,
        /// <summary>Completes a running intent, moving it to COMPLETED.</summary>
        COMPLETE = 3,
        /// <summary>Signals failure of a running intent, moving it to FAULTED.</summary>
        FAIL = 4,
        /// <summary>Prepares a created intent without activating, moving it to INACTIVE.</summary>
        PREPARE = 5,
        /// <summary>Recovers a faulted intent, moving it back to PENDING.</summary>
        RECOVER = 6,
        /// <summary>Restarts a completed intent, moving it back to PENDING.</summary>
        RESTART = 7,
        /// <summary>Resumes a blocked intent (e.g., after child completion), moving it back to RUNNING.</summary>
        RESUME = 8,
        /// <summary>Spawns a child process, moving the intent to BLOCKED.</summary>
        SPAWN_CHILD = 9,
        /// <summary>Starts a pending intent, moving it to RUNNING.</summary>
        START = 10,
    }

    /// <summary>The total number of defined events.</summary>
    public const int EventIdCount = 11;

    /// <summary>
    /// The possible states of the intent machine.
    /// </summary>
    public enum StateId
    {
        /// <summary>The root state containing all other states.</summary>
        ROOT = 0,
        /// <summary>The intent is waiting for a child process or external condition.</summary>
        BLOCKED = 1,
        /// <summary>The intent has been cancelled.</summary>
        CANCELLED = 2,
        /// <summary>The intent has successfully completed.</summary>
        COMPLETED = 3,
        /// <summary>The initial state upon creation.</summary>
        CREATED = 4,
        /// <summary>The intent has failed.</summary>
        FAULTED = 5,
        /// <summary>The intent is prepared but not yet active.</summary>
        INACTIVE = 6,
        /// <summary>The intent is ready to run but hasn't started yet.</summary>
        PENDING = 7,
        /// <summary>The intent is actively executing.</summary>
        RUNNING = 8,
    }

    /// <summary>The total number of defined states.</summary>
    public const int StateIdCount = 9;

    // Used internally by state machine. Feel free to inspect, but don't modify.
    /// <summary>
    /// The current state identifier.
    /// </summary>
    public StateId stateId;

    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    /// <summary>
    /// Initializes a new instance of the <see cref="IntentState"/> struct.
    /// </summary>
    public IntentState()
    {
    }

    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    /// <summary>
    /// Starts the state machine, transitioning to the initial state (CREATED).
    /// </summary>
    public void Start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.

            // ROOT.<InitialState> behavior
            // uml: TransitionTo(CREATED)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `CREATED`.
                CREATED_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }

    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    /// <summary>
    /// Dispatches an event to the state machine to trigger a transition.
    /// </summary>
    /// <param name="eventId">The event to dispatch.</param>
    public void DispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: IntentState
            case StateId.ROOT:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: BLOCKED
            case StateId.BLOCKED:
                switch (eventId)
                {
                    case EventId.RESUME: BLOCKED_resume(); break;
                    case EventId.ABORT: BLOCKED_abort(); break;
                    case EventId.CANCEL: BLOCKED_cancel(); break;
                }
                break;

            // STATE: CANCELLED
            case StateId.CANCELLED:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: COMPLETED
            case StateId.COMPLETED:
                switch (eventId)
                {
                    case EventId.RESTART: COMPLETED_restart(); break;
                }
                break;

            // STATE: CREATED
            case StateId.CREATED:
                switch (eventId)
                {
                    case EventId.PREPARE: CREATED_prepare(); break;
                    case EventId.ACTIVATE: CREATED_activate(); break;
                    case EventId.CANCEL: CREATED_cancel(); break;
                }
                break;

            // STATE: FAULTED
            case StateId.FAULTED:
                switch (eventId)
                {
                    case EventId.RECOVER: FAULTED_recover(); break;
                    case EventId.CANCEL: FAULTED_cancel(); break;
                }
                break;

            // STATE: INACTIVE
            case StateId.INACTIVE:
                switch (eventId)
                {
                    case EventId.ACTIVATE: INACTIVE_activate(); break;
                    case EventId.CANCEL: INACTIVE_cancel(); break;
                }
                break;

            // STATE: PENDING
            case StateId.PENDING:
                switch (eventId)
                {
                    case EventId.START: PENDING_start(); break;
                    case EventId.CANCEL: PENDING_cancel(); break;
                }
                break;

            // STATE: RUNNING
            case StateId.RUNNING:
                switch (eventId)
                {
                    case EventId.COMPLETE: RUNNING_complete(); break;
                    case EventId.SPAWN_CHILD: RUNNING_spawn_child(); break;
                    case EventId.FAIL: RUNNING_fail(); break;
                    case EventId.CANCEL: RUNNING_cancel(); break;
                }
                break;
        }

    }

    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void ExitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case StateId.BLOCKED: BLOCKED_exit(); break;

                case StateId.CANCELLED: CANCELLED_exit(); break;

                case StateId.COMPLETED: COMPLETED_exit(); break;

                case StateId.CREATED: CREATED_exit(); break;

                case StateId.FAULTED: FAULTED_exit(); break;

                case StateId.INACTIVE: INACTIVE_exit(); break;

                case StateId.PENDING: PENDING_exit(); break;

                case StateId.RUNNING: RUNNING_exit(); break;

                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////

    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state BLOCKED
    ////////////////////////////////////////////////////////////////////////////////

    private void BLOCKED_enter()
    {
        this.stateId = StateId.BLOCKED;
    }

    private void BLOCKED_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void BLOCKED_abort()
    {
        // BLOCKED behavior
        // uml: ABORT TransitionTo(FAULTED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            BLOCKED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `FAULTED`.
            FAULTED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for BLOCKED

        // No ancestor handles this event.
    }

    private void BLOCKED_cancel()
    {
        // BLOCKED behavior
        // uml: CANCEL TransitionTo(CANCELLED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            BLOCKED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `CANCELLED`.
            CANCELLED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for BLOCKED

        // No ancestor handles this event.
    }

    private void BLOCKED_resume()
    {
        // BLOCKED behavior
        // uml: RESUME TransitionTo(RUNNING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            BLOCKED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `RUNNING`.
            RUNNING_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for BLOCKED

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state CANCELLED
    ////////////////////////////////////////////////////////////////////////////////

    private void CANCELLED_enter()
    {
        this.stateId = StateId.CANCELLED;
    }

    private void CANCELLED_exit()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state COMPLETED
    ////////////////////////////////////////////////////////////////////////////////

    private void COMPLETED_enter()
    {
        this.stateId = StateId.COMPLETED;
    }

    private void COMPLETED_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void COMPLETED_restart()
    {
        // COMPLETED behavior
        // uml: RESTART TransitionTo(PENDING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            COMPLETED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PENDING`.
            PENDING_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for COMPLETED

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state CREATED
    ////////////////////////////////////////////////////////////////////////////////

    private void CREATED_enter()
    {
        this.stateId = StateId.CREATED;
    }

    private void CREATED_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void CREATED_activate()
    {
        // CREATED behavior
        // uml: ACTIVATE TransitionTo(PENDING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            CREATED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PENDING`.
            PENDING_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for CREATED

        // No ancestor handles this event.
    }

    private void CREATED_cancel()
    {
        // CREATED behavior
        // uml: CANCEL TransitionTo(CANCELLED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            CREATED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `CANCELLED`.
            CANCELLED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for CREATED

        // No ancestor handles this event.
    }

    private void CREATED_prepare()
    {
        // CREATED behavior
        // uml: PREPARE TransitionTo(INACTIVE)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            CREATED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `INACTIVE`.
            INACTIVE_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for CREATED

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state FAULTED
    ////////////////////////////////////////////////////////////////////////////////

    private void FAULTED_enter()
    {
        this.stateId = StateId.FAULTED;
    }

    private void FAULTED_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void FAULTED_cancel()
    {
        // FAULTED behavior
        // uml: CANCEL TransitionTo(CANCELLED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            FAULTED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `CANCELLED`.
            CANCELLED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for FAULTED

        // No ancestor handles this event.
    }

    private void FAULTED_recover()
    {
        // FAULTED behavior
        // uml: RECOVER TransitionTo(PENDING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            FAULTED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PENDING`.
            PENDING_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for FAULTED

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state INACTIVE
    ////////////////////////////////////////////////////////////////////////////////

    private void INACTIVE_enter()
    {
        this.stateId = StateId.INACTIVE;
    }

    private void INACTIVE_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void INACTIVE_activate()
    {
        // INACTIVE behavior
        // uml: ACTIVATE TransitionTo(PENDING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            INACTIVE_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PENDING`.
            PENDING_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for INACTIVE

        // No ancestor handles this event.
    }

    private void INACTIVE_cancel()
    {
        // INACTIVE behavior
        // uml: CANCEL TransitionTo(CANCELLED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            INACTIVE_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `CANCELLED`.
            CANCELLED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for INACTIVE

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PENDING
    ////////////////////////////////////////////////////////////////////////////////

    private void PENDING_enter()
    {
        this.stateId = StateId.PENDING;
    }

    private void PENDING_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void PENDING_cancel()
    {
        // PENDING behavior
        // uml: CANCEL TransitionTo(CANCELLED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            PENDING_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `CANCELLED`.
            CANCELLED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PENDING

        // No ancestor handles this event.
    }

    private void PENDING_start()
    {
        // PENDING behavior
        // uml: START TransitionTo(RUNNING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            PENDING_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `RUNNING`.
            RUNNING_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PENDING

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state RUNNING
    ////////////////////////////////////////////////////////////////////////////////

    private void RUNNING_enter()
    {
        this.stateId = StateId.RUNNING;
    }

    private void RUNNING_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void RUNNING_cancel()
    {
        // RUNNING behavior
        // uml: CANCEL TransitionTo(CANCELLED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            RUNNING_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `CANCELLED`.
            CANCELLED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for RUNNING

        // No ancestor handles this event.
    }

    private void RUNNING_complete()
    {
        // RUNNING behavior
        // uml: COMPLETE TransitionTo(COMPLETED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            RUNNING_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `COMPLETED`.
            COMPLETED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for RUNNING

        // No ancestor handles this event.
    }

    private void RUNNING_fail()
    {
        // RUNNING behavior
        // uml: FAIL TransitionTo(FAULTED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            RUNNING_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `FAULTED`.
            FAULTED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for RUNNING

        // No ancestor handles this event.
    }

    private void RUNNING_spawn_child()
    {
        // RUNNING behavior
        // uml: SPAWN_CHILD TransitionTo(BLOCKED)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            RUNNING_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `BLOCKED`.
            BLOCKED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for RUNNING

        // No ancestor handles this event.
    }

    // Thread safe.
    /// <summary>
    /// Converts a <see cref="StateId"/> to its string representation.
    /// </summary>
    /// <param name="id">The state ID.</param>
    /// <returns>The string name of the state.</returns>
    public static string StateIdToString(StateId id)
    {
        switch (id)
        {
            case StateId.ROOT: return "ROOT";
            case StateId.BLOCKED: return "BLOCKED";
            case StateId.CANCELLED: return "CANCELLED";
            case StateId.COMPLETED: return "COMPLETED";
            case StateId.CREATED: return "CREATED";
            case StateId.FAULTED: return "FAULTED";
            case StateId.INACTIVE: return "INACTIVE";
            case StateId.PENDING: return "PENDING";
            case StateId.RUNNING: return "RUNNING";
            default: return "?";
        }
    }

    // Thread safe.
    /// <summary>
    /// Converts a <see cref="EventId"/> to its string representation.
    /// </summary>
    /// <param name="id">The event ID.</param>
    /// <returns>The string name of the event.</returns>
    public static string EventIdToString(EventId id)
    {
        switch (id)
        {
            case EventId.ABORT: return "ABORT";
            case EventId.ACTIVATE: return "ACTIVATE";
            case EventId.CANCEL: return "CANCEL";
            case EventId.COMPLETE: return "COMPLETE";
            case EventId.FAIL: return "FAIL";
            case EventId.PREPARE: return "PREPARE";
            case EventId.RECOVER: return "RECOVER";
            case EventId.RESTART: return "RESTART";
            case EventId.RESUME: return "RESUME";
            case EventId.SPAWN_CHILD: return "SPAWN_CHILD";
            case EventId.START: return "START";
            default: return "?";
        }
    }
}
