@startuml
!theme sunlust

/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "CSharp"
'/

[*] --> CREATED

CREATED --> WAITING_FOR_ACTIVATION : GET_READY
CREATED --> WAITING_TO_RUN : ACTIVATED

WAITING_FOR_ACTIVATION --> WAITING_TO_RUN : ACTIVATED

WAITING_TO_RUN --> RUNNING : START_RUNNING
WAITING_TO_RUN --> CANCELED : CANCELED_BEFORE_RUN

WAITING_FOR_ACTIVATION --> CANCELED : CANCELED_BEFORE_ACTIVATION

RUNNING --> WAITING_FOR_CHILDREN_TO_COMPLETE : CHILD_TASK_CREATED
RUNNING --> FAULTED : UNABLE_TO_COMPLETE
RUNNING --> CANCELED : CANCEL
RUNNING --> RAN_TO_COMPLETION : COMPLETED_SUCCESSFULLY

WAITING_FOR_CHILDREN_TO_COMPLETE --> RUNNING : ALL_CHILDREN_COMPLETED

RAN_TO_COMPLETION --> WAITING_TO_RUN : RUN_AGAIN

@enduml
