namespace GameVariable.Intent;

/// <summary>
///     A high-performance, zero-allocation Hierarchical State Machine (HSM) for managing intent and logic flow.
/// </summary>
/// <remarks>
///     <para>
///         This struct is autogenerated by StateSmith and implements a flat, optimized state machine.
///         It is designed to be used as a field in other structs or classes to manage complex state logic without GC
///         overhead.
///     </para>
///     <para>
///         The state machine handles events such as <see cref="EventId.ACTIVATED" />, <see cref="EventId.CANCEL" />,
///         and <see cref="EventId.COMPLETED_SUCCESSFULLY" /> to transition between states like
///         <see cref="StateId.WAITING_FOR_ACTIVATION" />, <see cref="StateId.RUNNING" />, and
///         <see cref="StateId.RAN_TO_COMPLETION" />.
///     </para>
/// </remarks>
public partial struct IntentState
{
}
